import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "../../i18n/routing";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children,
  params // Accept params as is (no need to await)
}) {
  const { locale } = await params; // Just directly access the params object

  // Check if the locale is supported
  if (!routing.locales.includes(locale)) {
    notFound();
  }

  // Fetch messages for the locale
  const message = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={message}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
